version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    container_name: my-mysql
    ports:
      - 3308:3306
    volumes:
      - mysql-volume:/var/lib/mysql
  my-app:
    build: .
    image: my-app:v1
    ports:
      - 8080:8080
    container_name: my-app-container
    depends_on:
      - db
  client:
    image: client-app:v1
    ports:
      - 8181:8080
    container_name: client-app-container
    depends_on:
      - my-app
volumes:
  mysql-volume:
